name: CD

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: 'C:\Users\runneradmin\AppData\Roaming\stack'
          key: ${{ runner.os }}-store-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('wsl-backup.cabal') }}
      - name: Cache GHC
        uses: actions/cache@v2
        with:
          path: 'C:\Users\runneradmin\AppData\Local\Programs\stack'
          key: ghc-${{ hashFiles('stack.yaml.lock') }}
      - name: Build
        run: stack build --copy-bins
      - name: Upload assets
        uses: softprops/action-gh-release@v1
        with:
          files: dist/wsl-backup.exe
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
