name: CI

on: [pull_request, push]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: "9.0.1"
          enable-stack: true
          stack-version: "latest"
      - name: Compile
        run: stack build --copy-bins
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          token: ${{ secrets.PAT }}
      - name: Semantic release
        uses: cycjimmy/semantic-release-action@v2.5.4
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
